version: '3.8'

services:
  web:
    container_name: vulnerable_app
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=linh
      - MYSQL_DATABASE=LINUS_OSS

  mysql:
    container_name: db_for_vuln_web
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=linh
      - MYSQL_DATABASE=LINUS_OSS
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./SQL:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
