
FROM node:23.3.0

# Set environment variables
ENV APP_DIR=/var/www/html/vul_web

# Set the working directory
WORKDIR $APP_DIR

RUN chmod -R 777 ${APP_DIR}

# Copy package.json and package-lock.json to optimize Docker caching
COPY package.json package-lock.json ./

# Install project dependencies using npm ci for a clean and repeatable install
RUN  npm ci

# Copy the rest of the application files
COPY . .
# Start the application
CMD ["npm", "run", "server"]

# Expose the port the app will run on (this can be after CMD as well)
EXPOSE 3000
